public/clientJS/wishCard.js, views/wishCards.ejs
Right click on child image is disabled. This still can not prevent someone from downloading it but it will make things a bit more complex for those who do not know.
=> Disable right click

views/signup.ejs
=> removed duplicate jquery tag

public/clientJS/agency.js, routes/users.js, views/agency.ejs, views/profile.ejs
Issue fix:
- Agency creation/redirection
- Agency is now created on DB, users are then redirected to profile page.
=> Issue fix 

public/clientJS/profile.js, public/clientJS/wishCard.js
On firefox right click was still working, since path prop was not supported there. Swtiched to target which works on edge, firefox, chrome.
Added a small check if an error is returned from backend that prevents from appending about me info if error is present.
=>  @Tokikko Change proprety when disabling right click

public/css/home.css, public/css/signup.css, views/wishCards.ejs
=> Wishcards: adjust card for mobile responsiveness

public/css/signup.css, views/login.ejs, views/signup.ejs
=> Sign up: adjust for mobile responsiveness

readme.md, routes/users.js, views/profile.ejs
Added agency info to profile page when displaying user that has a "partner" role.
Fixed small typo in catch block.
Changed my name :)
=> Added agency info to profile page

public/clientJS/signup.js, readme.md, routes/users.js, views/signup.ejs
Added confirm password field on signup form.
Implemented toast message
(from https://github.com/apvarun/toastify-js)
I have loaded it through cdn and only on signup page but if you are happy with it we can add it through npm.
Did a small refactor on signup js so that we do not have to add a separate error handler for each status code
=> Added toast, confirm password

public/clientJS/agency.js, public/clientJS/profile.js, public/clientJS/signup.js, public/clientJS/simpleToast.js, public/css/toast.css, views/signup.ejs, views/templates/footer.ejs
Moved css nad js files required for toas into footer since they are used everywhere on the site.
Wrapped the call to make toast inside a function since the design is the same for every page, only the message is changing.
Replace alerts with toast messages
=> Toast modifications

public/css/home.css
=> Restrict size of images, hide overflow

public/css/home.css, views/templates/homeSampleCards.ejs
This should work I just need to test it out...
Can you please add a test card with the interest section containing more than 130 characters? 
Or show me how to use a test account and add cards :sweat_smile:
=> Add min-height to text container in wish card, add logic to render ellipsis

app.js, routes/users.js
Finally, lmao!
- Changed to findByIdAndUpdate (as a transaction to avoid race conditions in future)
- Slightly changed middleware in app
- Ensured that both req is updated as well (when changes are made to user/agency)
=> DON-9 userprofile

views/wishCards.ejs
Bug fix for wishcards page
- Unauthenticated users
- Added a check to ensure `user` variable is not null.
=> DON-18 wishcards bug fix

routes/validations/users.validations.js, test/users.test.js, views/agency.ejs
Note: I had made the change to Toast display on DON-17 PR (hadn't realized that there was a ticket at the time). Anyways, few more things to add:
- Marked AgencyName and Phone as required on frontend form
- Changed the order of validations (not empty check first)
- Added tests for agency form validation
=> DON-16-ValidationErrorsDisplay

public/clientJS/passwordReset.js, views/resetPassword.ejs
Added password reset validation on frontend
=> Password reset

public/clientJS/requestPassword.js, public/clientJS/utils.js, views/requestPassword.ejs
Added frontend validation to request password page
=> Request page

client/public/css/error.css, client/views/about.ejs, client/views/error.ejs, server/app.js
=> feat: created generic 404 error page

client/public/clientJS/about.js, client/views/about.ejs, package-lock.json, package.json, server/controller/messaging.js, server/routes/about.js, server/routes/users.js
we now  use slack instead of email for feedback form
=> feat: added slack integration

server/db/models/WishCard.js, server/db/repository/AgencyRepository.js, server/db/repository/WishCardRepository.js, server/routes/wishCards.js
Added endpoint for getting wishcards for current agency that belongs to user (agency/me).
Created new status field on wishcard model
=> Endpoint for wishcards

client/public/clientJS/profile.js, client/views/profile.ejs, server/routes/users.js
Added checkbox on wishcard creation. If users select it it will prefill wishcard address form with agency address
=> Checkbox for agency address

client/public/css/home.css, client/views/home.ejs, client/views/templates/loginModal.ejs, client/views/templates/nav.ejs, client/views/wishCards.ejs
- Creates login modal
- Triggered on donate button if user is not logged in
- Didn't style the oauth buttons
- ignore Last pass icons within input fields
`! Important: this needs testing. I couldn't get local wishcards populated..`
=> DON-24: Create login modal, needs styling

client/public/clientJS/wishCardModal.js, client/views/templates/wishCardDonateModal.ejs
merging Jacob's spinner (part3) to the donation modals
=> Donation modal

client/public/clientJS/wishCardModal.js, client/public/css/home.css, client/views/templates/wishCardDonateModal.ejs
Adjust layout of buttons as well as prevents modal
from being closed in certain situations.
Resolves: DON-103, DON-35
=> Adjust donate modal button layout

client/public/css/home.css, client/public/img/chevron-left.svg, client/public/img/chevron-right.svg, client/views/templates/homeSampleCards.ejs, server/routes/wishCards.js
- Merging wishcardcarousel with new changes
=> WishCardCarousel

client/public/clientJS/wishCard.js, client/public/clientJS/wishCardModal.js, client/views/wishCards.ejs, server/db/repository/WishCardRepository.js, server/db/seeder.js, server/routes/wishCards.js, test/wishcards.test.js
buttons get locked now if a donation is confirmed
some cleanup
status is set properly in wishcards if donation is confirmed
=> bug: scraper returns properly now

client/public/clientJS/loginModal.js, client/public/clientJS/socialLogin.js, client/views/login.ejs, client/views/wishCards.ejs, server/routes/users.js, server/routes/wishCards.js
LoginModal Adjustments
- LoginModal reloads the page, rather than redirecting.
- Few other adjustments needed to be made to facilitate this, since /login route was redirecting on success and rendering login page (with errorMessages) on failure.
- Now, it will simply send an object in either case (with url for redirection and errorMessages - both of which are handled in the client side).
Update: ~~Also fixed a minor error with messages (redirectLogin rather than renderPermissions. Latter limited messaging to only agency users - which was a bug).~~
Some changes need to be made for tests as well, keeping that for another ticket since it's not related. Originally had kept it with this since it was a one line change.
=> Don 126 login modal

client/views/agencyWishCards.ejs, client/views/templates/nav.ejs, server/db/models/User.js, server/db/repository/AgencyRepository.js, server/routes/users.js, server/routes/wishCards.js
- /users/agency/wishcards -> /wishcards/me
Both routes were present, but only the former was used for functionality; I moved the logic for former into latter (which is now used for rendering agencyWishcards aka _My Wishcards_ page.
Also added logic to agencyWishcards for displaying wishcards based on status (Need to be beautified further; as well as add edit/delete functionality to draft wishcards).
- Bug fix
Wishcards created using guided route were not being pushed to their respective agencies. Added logic for that. POST routes were also pushing wishcards directly, rather than the id, so fixed that as well. We might have to look into production, if any agencies have used guided route for Wishcard creation (luckily, we do have the createdBy field to go on, but we will have to fix it).
- …
=> WishCard fixes

client/public/css/home.css, client/public/css/utils.css, client/views/home.ejs, client/views/templates/homeSampleCards.ejs
Home cards are no longer cut off. Fixed shadows for all cards for consistency. Altered arrows for both home carousels to look the same.
=> Slight touch up on carousels

client/public/clientJS/loginToast.js, client/public/css/toast.css
Added login toast message to be responsive for phones plus new CSS styles.
=> Login Toast Responsive for phones

server/routes/middleware/wishCard.middleware.js, server/routes/wishCards.js, test/wishcards.test.js
- Added test cases for donor users (email verified and email unverified)
- Fixed message permissions bug (Messaging was restricted to agency users on backend -> now it's open to all verified Donor users)
- DON-130 Route bug
- Changed GET route to display all wishcards, rather than one with published status (will have to update once we add edit/publish functionality)
=> Don 128 wishcard tests + DON-130

client/public/clientJS/adminWishCards.js, package-lock.json
When replacing the url of an item new address was not being taken if entered
=> Fixed bug when new address was not taken

client/views/wishCardFullPage.ejs
Disabled donate button when clicking on read more
=> Disabled button

client/public/clientJS/wishCard.js, client/public/clientJS/wishCardModal.js, server/routes/wishCards.js
- Wishcard routes
- Added checkVerifiedUser validation for donation routes (card lock/unlock)
- WishCard
- Replaced isLoggedIn with emailVerified
- WishCardModal
- Displays verify email message for unverified accounts (on donate button click)
- Additional adjustments for better readability
- added parameters for showLoadingView function (donateBtnWrapped and lockedCountdown)
- This was required as earlier logic was not working as intended
- Resulting in countdown being displayed at the same time as Donation Confirmed message
- Moved scraping logic to their own functions (simulateScrape vs Scrape)
- Added timeout for simulating a scrape for local dev
- helps with mocking UX
=> Don 141 unverified donations

client/public/clientJS/wishCard.js, client/views/wishCards.ejs, server/routes/controller/wishcard.controller.js, server/routes/wishCards.js
=> fix for default search values

client/public/clientJS/wishCard.js, client/public/clientJS/wishCardModal.js, server/routes/wishCards.js
Reverts donategifts/donategifts#208
=> Revert "Don 141 unverified donations"

client/public/css/home.css, client/views/wishCards.ejs
Change layout of filter UI to better communicate that filters need to be applied after being selected.
=> Update wish card search/filter UI

client/public/css/home.css, client/views/wishCards.ejs
These changes are based on a revised design for mobile and desktop
=> Update search filter UI

client/public/css/stripe.css, client/views/donate.ejs
=> Payment UI

client/public/clientJS/wishCard.js, client/views/templates/homeSampleCards.ejs
- Similar logic to donate Btn
- Displays login modal for unauthenticated user
- Link for logged in user
Hmm, should we should display a similar modal + message for email unverified users (Just a message to verify their email) @gnorbsl @stacysealky  🤔
=> DON-160-LoginModal for Read more

client/public/css/community.css, client/views/community.ejs
=> Community page skeleton

server/routes/wishCards.js
* package ugh
* minor css change
* didn't change anything, just merging
* feat: added load more, refined wishcard search (#205)
* feat: added load more, refined wishcard search
* fix: tests
* added slack notifications for donations
* Donation Verification
- Wishcard routes
- Added checkVerifiedUser validation for donation routes (card lock/unlock)
- WishCard
- Replaced isLoggedIn with emailVerified
- WishCardModal
- Displays verify email message for unverified accounts (on donate button click)
- Additional adjustments for better readability
- added parameters for showLoadingView function (donateBtnWrapped and lockedCountdown)
- This was required as earlier logic was not working as intended
- Resulting in countdown being displayed at the same time as Donation Confirmed message
* Adjusting …
=> birthday hotfix (#256)

server/routes/wishCards.js
If the number of published cards is less than 6, random fn will push donated cards as well (to be displayed on front page carousel).
=> Display Donated cards

server/routes/wishCards.js
- Changed to getByStatus (to fetch only donated cards)
- Avoids duplicates (getViewableCards would return published cards as well)
=> wishCardRandom

packages/helper/src/email/index.ts, packages/helper/src/email/types/IDonationConfirmationEmail.ts, packages/helper/src/email/types/IEmail.ts, packages/helper/src/slack/index.ts, packages/helper/src/slack/types/IDonationSlack.ts, packages/helper/src/slack/types/ISlackFeedbackMsg.ts
- Added DonationConfirmation Email
- Added sendDonationNotificationToSlack
- Both are used in stripeRoutes (paymentController which is under development)
- Added types for these fns and sendEmail (all were used elsewhere/other routes in v1, so having the types helps later on)
=> Helper fns

.gitignore, package-lock.json, packages/helper/src/email/index.ts, packages/helper/src/email/resources/donorDonationReceipt.html
fix: added config.env to gitignore
=> fix: fixed missing file and wrong path for email helper

client/views/profile.ejs, server/app.js, server/db/repository/AgencyRepository.js, server/helper/logger.js, server/routes/users.js
it's not needed there and this way we avoid spamming the server with socket requests in the profile section
@gnorbsl @stacysealky
=> removed footer from profile page

client/public/clientJS/wishCard.js, client/public/clientJS/wishCardModal.js, client/public/css/wishCardFull.css, client/views/templates/homeSampleCards.ejs, client/views/wishCardFullPage.ejs, nodemon.json, server/routes/wishCards.js, test/wishcards.test.js
=> made wishcard details visible for not logged in users

views/pages/profile/overview.pug
I've fix the frontend bug for /profile page edit features, but when I reload the page, the user account infomation (fName, lName, aboutMe) didn't update although the data has been sent in the request payload when I opened DevTools (I also check if the info has been updated in Mongo Compass, yes it was), and only when I sign out and log in again the information becomes up-to-date
=> fix frontend bug for /profile page edit features

src/controller/profile.ts, src/db/repository/UserRepository.ts, views/pages/profile/overview.pug
=> Fix session user data not update properly after calling /profile update routes and updated in MongoDB

.husky/pre-commit, src/api/agency.ts, src/api/community.ts, src/api/controller/agency.ts, src/api/controller/basecontroller.ts, src/api/controller/community.ts, src/controller/community.ts, src/controller/profile.ts, src/db/repository/AgencyRepository.ts
=> refactor: api-controller

design/scss/_variables.scss
Updated property to remove deprecation by adding % sign.
Issue #590
=> chore: updated deprecated property

design/scss/_variables.scss, design/scss/custom/_faq.scss, views/pages/faq.pug
=> 612 faq page css update

src/api/controller/community.ts, src/controller/wishcard.ts, types/express.d.ts
The location prop from aws was spelled as Location so i have extended the definition with it
=> Extended prop definition

src/controller/profile.ts, views/pages/profile/overview.pug
=> fix: email verification page

design/scss/custom/_profile.scss, src/api/controller/profile.ts, src/api/index.ts, src/api/profile.ts, views/pages/profile/overview.pug
added button to resend verification link
added new api route
fixed agency info update (duplicate ids on page)
=> new: added verification link resend option

js/react/utils/helpers.jsx, views/pages/signup/basecontact.pug
=> fix: password repeat error message

views/components/modal/signupModal.pug
redesigned sign up with current theme colors and font-awesome icons
resolves #568
=> update: sign up modal redesign

js/react/components/wishcards/index.jsx
#698 - removed the semicolon for the code 
@Enubia
=> #698: removed the semicolon

design/scss/custom/_home.scss, js/react/components/home/WishCardsCarousel.jsx, js/react/components/shared/WishCard.jsx, js/react/components/wishcards/index.jsx, views/pages/home.pug
=> fix: carousel clipping and wishcard style

js/react/pages/wishcard/WishCardCreate.jsx, src/api/controller/wishcards.ts, types/express.d.ts
=> fix: s3 file location

design/scss/_includes.scss, design/scss/custom/_verify.scss, src/controller/password.ts, src/controller/profile.ts, src/routes/login.ts, views/pages/login.pug, views/pages/passwordreset.pug, views/pages/passwordresetconfirmation.pug, views/pages/profile/overview.pug, views/pages/profile/verify.pug, views/partials/navbar.pug
we now show a verification page and redirect the user after 5 seconds to the profile
the session is also fixed now
resolves #715
resolves #720
=> fix: fixed email verification stuff

docker-compose.yml, src/controller/paymentProvider.ts, src/db/repository/AgencyRepository.ts
=> fix: fixed agency donation email sending

design/scss/custom/_wishcards.scss, js/react/components/shared/WishCard.jsx, js/react/forms/AgencyCardEditForm.jsx, js/react/pages/admin/routes/wishcard/administration.jsx, js/react/pages/wishcard/WishCardCreate.jsx, js/react/translations/en/forms.json, src/translations/en/forms.json, views/mixins/wishcards/cardLoader.pug, views/pages/wishcard/donate.pug, views/pages/wishcard/single.pug
- Fixed childImage (wishCardImage deprecated) display defect for new cards  (Resolves #642 )
- Changed wishItemPrice rule to max of $50 instead of $40 because of inflation
- Fixed minor things in admin page
- Replaced the file uploader button (previously input type="file")
=> File button uploader

design/scss/custom/_wishcards.scss, js/react/components/home/WishCardsCarousel.jsx, js/react/components/shared/WishCard.jsx, js/react/forms/AgencyCardEditForm.jsx, js/react/pages/admin/routes/wishcard/administration.jsx, js/react/pages/wishcard/WishCardCreate.jsx, js/react/translations/en/forms.json, src/controller/home.ts, src/db/repository/WishCardRepository.ts, src/translations/en/forms.json, views/mixins/wishcards/cardLoader.pug, views/pages/home.pug, views/pages/wishcard/donate.pug, views/pages/wishcard/single.pug
Curated carousel displays when there is 0 wishcard to be donated, so that the home page looks better.
=> Curated carousel

design/scss/custom/_community.scss, js/react/pages/community.jsx
Resolves #718 
- Fixed the post display order issue
Resolves #719 
- Added validation so when there's no message, user cannot post (previously it allowed empty posts).
- Cleaned up UI
=> 718, 719 Community Post

Contributing.md, src/controller/wishcard.ts
Added a condition that checks whether the new date format exists.
If it does, it's used to calculate child's age. If not, the old one is being used.
(assuming either of those is present)
added a line to Contributing.md about a docker config file.
=> #746 Modify the child's age in wish cards

js/react/bundle.jsx, js/react/components/Footer.jsx, views/master.pug
I converted the `footer.pug` file in views\partials\footer.pug to a react component in js/react/components/Footer.jsx.
This was requested in issue #744.
=> Converted footer.pug to a react component

design/scss/custom/_adminWishcards.scss, design/scss/custom/_home.scss, js/react/pages/admin/routes/agency/detail.jsx, js/react/pages/admin/routes/wishcard/administration.jsx, views/pages/home.pug
Resolves #758 
- Added a header and disclaimer for home sample carousel wishcards
Also Modified the Admin Wishcards Dashboard
- previously it was not showing the child's name (fixed)
- added more data
- added wish item check
@Tokikko @Enubia I have also noticed that the wishItemURL replacement input in the admin/wishcards is broken and does not update the URL. I created a separate issue #761
=> #758 and Admin Wishcards Enhancements

resources/email/verifyEmail.html
removed the public from logo url ,issue #766
=> removed public from logo url

design/scss/_variables.scss, design/scss/custom/_home.scss, js/react/components/shared/WishCard.jsx, js/react/pages/wishCards.jsx
Resolves #643 
- inner image slider added to display child image and wish item image
- made UI enhancements for wishcard design so that it looks cleaner and prettier
- made Donated button more visually disabled and added a disabled mouse pointer on hover
- functionality locally tested and passed
Resolves #770 
- redirects to /login instead of showing the broken modal for non-users
Before
After
=> #643 and #770 - New WishCard Design

js/react/pages/signup.jsx, views/pages/wishcard/donate.pug
hiding paypal button until fixed, 
aligned the g-signup button
=> quick fixes for prod

js/react/bundle.jsx, js/react/pages/contact.jsx, views/pages/contact.pug
I converted the `contact.pug` page to a react component in `contact.jsx`.
Closes #695.
=> Converted contact.pug to react

design/scss/custom/_donate.scss, design/scss/style.scss, js/react/bundle.jsx, js/react/components/shared/WishCard.jsx, js/react/pages/payment/success.jsx, src/api/controller/payment.ts, src/api/controller/wishcards.ts, src/api/index.ts, src/api/payment.ts, src/api/wishcards.ts, views/components/modal/checkoutHelperModals.pug, views/pages/payment/success.pug, views/pages/wishcard/donate.pug, views/pages/wishcard/single.pug
Resolves #794 
- Converted payment success page from Pug to React
- Redesigned the UI 
- Added the Custom Message section
- Added backend API route and controller and updated the postMessage function
- Added frontend validation for custom message, so empty message will show field error immediately and won't be sent
- Added suggested wish cards on the bottom section
- Added edge case checks for suggested wish cards
**Before Changes:** 
**After Changes:**
Default Screen
Message Sent
When there's no wish card left for suggested cards
=> 794-Payment-Success

js/react/components/home/WishCardsCarousel.jsx, js/react/components/shared/WishCard.jsx, package-lock.json, package.json
- Converted bootstrap carousel to Mantine instead (mimicking the inner card carousel)
- Installed embla-carousel-autoplay plugin for auto loop
=> Carousel fix

js/react/pages/wishCards.jsx, src/controller/wishcard.ts, views/pages/wishcards.pug
Added search bar and filtering options, may need additional styling though, but functionality is good to go.
=> Search and Filtering

js/react/pages/wishCards.jsx, src/controller/wishcard.ts, views/pages/wishcards.pug
This reverts commit 11e2b0241f6965240eed2c8eedcc8e1dec290311.
=> Revert "Search and Filtering (#823)"

js/react/components/auth/login/LoginWithEmail.jsx, js/react/components/forms/MessageForm.jsx, js/react/components/shared/CustomToast.jsx, js/react/components/shared/PopOver.jsx, js/react/pages/admin/routes/donations.jsx, js/react/pages/admin/routes/wishcard/administration.jsx, js/react/pages/profile/donationhistory.jsx, js/react/pages/wishcard/create.jsx, js/react/pages/wishcard/single.jsx
=> update: make wishcards prettier

js/react/pages/wishCards.jsx, src/controller/wishcard.ts, views/pages/wishcards.pug
#823 
+
- added logic to rerender when user clicks on any of the filtering options (rather than having to click submit).
- only display agencies with wishcards in the agency sort dropdown (and ordered them alphabetically)
- Added no results message for now (maybe do additional styling?)
Note: Still has to use submit button for the text input ofc.
=> 810 searchbar component

js/react/bundle.jsx, js/react/components/wishcards/SearchBar.jsx, js/react/pages/wishcards.jsx, js/react/utils/mantineProviderWrapper.jsx
added a floating sticky menu for the filter options
=> update: added new filter options design

js/react/components/wishcards/SearchBar.jsx
Wishcards Search / Filter bar
- fixed the select dropdown duplicate option render error
=> fixed the select dropdown duplicate option render error

js/react/components/wishcards/SearchBar.jsx, js/react/pages/wishcards.jsx, src/controller/wishcard.ts, src/db/repository/WishCardRepository.ts, views/pages/wishcards.pug
Added price slider and sort by price.
=> Filter price slider

js/react/components/shared/PopOver.jsx, views/pages/team.pug
reverted popover to onClick, removed information from teams
=> reverted popover to onClick, removed information from teams

js/react/components/wishcards/SearchBar.jsx
Modified close params (close on click) for user friendliness on mobile.
=> Agency Filtering on Mobile

js/react/components/forms/AgencyCardEditForm.jsx, js/react/pages/wishcard/manage.jsx, src/api/controller/wishcards.ts, src/api/wishcards.ts
- Added logic to enable editing on wishcard edit form (partners)
- Modified handlePutAgencyWishCardById route to allow for image updates
=> Wishcard Edit Form: Images

js/react/pages/admin/routes/router.jsx, js/react/pages/admin/routes/wishcard/administration.jsx, js/react/pages/admin/routes/wishcard/wishcardDetail.jsx, src/api/admin.ts, src/api/controller/admin.ts
Edit both child and wishItem images on administration panel. The wishcard state has all the other props, in case we need to make all the other fields editable on admin end.
=> Admin: Wishcard Images Edit

js/react/pages/wishcard/manage.jsx, src/api/controller/wishcards.ts, src/api/wishcards.ts, src/middleware/validations.ts
#706 I know the issue mentioned adding delete button directly under the edit button, but I thought this would be better on mobile and such (esp to folks who have fatter fingers lol).
=> Agency Wishcards Delete
